%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: Dockerfile

file_extensions:
  - Dockerfile
  - Containerfile
  - dockerfile
  - containerfile

scope: source.dockerfile

contexts:
  main:
    - include: comments
    - include: instructions
    - include: strings
    - include: variables
    - include: numbers

  comments:
    - match: '^\s*#.*$'
      scope: comment.line.number-sign.dockerfile

  instructions:
    - match: |-
        (?ix)^\s*(
          FROM|RUN|CMD|LABEL|MAINTAINER|EXPOSE|ENV|ADD|COPY|ENTRYPOINT|VOLUME
          |USER|WORKDIR|ARG|ONBUILD|STOPSIGNAL|HEALTHCHECK|SHELL
        )\b
      scope: keyword.control.instruction.dockerfile
    - match: '(?i)\b(AS|FROM)\b'
      scope: keyword.control.instruction.dockerfile

  variables:
    - match: '\$\{[A-Za-z_][A-Za-z0-9_]*(:[-=+?][^}]*)?\}'
      scope: variable.parameter.dockerfile
    - match: '\$[A-Za-z_][A-Za-z0-9_]*'
      scope: variable.parameter.dockerfile

  numbers:
    - match: '\b[0-9]+\b'
      scope: constant.numeric.dockerfile

  strings:
    - match: '"'
      scope: punctuation.definition.string.begin.dockerfile
      push:
        - meta_scope: string.quoted.double.dockerfile
        - match: '\\.'
          scope: constant.character.escape.dockerfile
        - match: '"'
          scope: punctuation.definition.string.end.dockerfile
          pop: true
    - match: "'"
      scope: punctuation.definition.string.begin.dockerfile
      push:
        - meta_scope: string.quoted.single.dockerfile
        - match: "'"
          scope: punctuation.definition.string.end.dockerfile
          pop: true
